export const characters = [
    { slug: "aki", displayName: "A.K.I", file: "Aki"},
    { slug: "blanka", displayName: "ブランカ", file: "Blanka"},
    { slug: "cammy", displayName: "キャミィ", file: "Cammy"},
    { slug: "chunli", displayName: "春麗", file: "Chunli"},
    { slug: "deejay", displayName: "Dee-Jay", file: "Deejay"},
    { slug: "dhalsim", displayName: "ダルシム", file: "Dhalsim"},
    { slug: "ed", displayName: "エド", file: "Ed"},
    { slug: "elena", displayName: "エレナ", file: "Elena"},
    { slug: "gouki", displayName: "豪鬼", file: "Gouki"},
    { slug: "guile", displayName: "ガイル", file: "Guile"},
    { slug: "honda", displayName: "エドモンド本田", file: "Honda"},
    { slug: "jamie", displayName: "ジェイミー", file: "Jamie"},
    { slug: "jp", displayName: "JP", file: "Jp"},
    { slug: "juri", displayName: "ジュリ", file: "Juri"},
    { slug: "ken", displayName: "ケン", file: "Ken"},
    { slug: "kimberly", displayName: "キンバリー", file: "Kimberly"},
    { slug: "lily", displayName: "リリー", file: "Lily"},
    { slug: "luke", displayName: "ルーク", file: "Luke"},
    { slug: "mai", displayName: "舞", file: "Mai"},
    { slug: "manon", displayName: "マノン", file: "Manon"},
    { slug: "marisa", displayName: "マリーザ", file: "Marisa"},
    { slug: "rashid", displayName: "ラシード", file: "Rashid"},
    { slug: "ryu", displayName: "リュウ", file: "Ryu"},
    { slug: "terry", displayName: "テリー", file: "Terry"},
    { slug: "vega", displayName: "ベガ", file: "Vega"},
    { slug: "zangief", displayName: "ザンギエフ", file: "Zangief"},
]